name: 'Sous Layout Builder'
description: 'A recipe that contains default configuration for Sous layout builder.'
type: 'Sous'
recipes:
  - sous-content-types
install:
  # Install core dependencies.
  - block_content
  - gin_lb
  - layout_builder
  - layout_builder_browser
  - layout_discovery
  - options
config:
  actions:
    core.entity_view_display.node.page.default:
      simple_config_update:
        dependencies:
          module:
            - layout_builder
        third_party_settings:
          layout_builder:
            enabled: true
            allow_custom: true
            sections:
              -
                layout_id: layout_onecol
                layout_settings:
                  label: ''
                components: {  }
                third_party_settings: {  }
        hidden:
          layout_builder__layout: true
    core.entity_view_display.node.page.teaser:
      simple_config_update:
        dependencies:
          module:
            - layout_builder
        hidden:
          layout_builder__layout: true
    core.entity_form_display.node.page.default:
      simple_config_update:
        dependencies:
          config:
            - field.field.node.page.layout_builder__layout
        hidden:
          layout_builder__layout: true
    gin_lb.settings:
      simple_config_update:
        toastify_loading: custom
        save_behavior: default
